trigger:
  - master

variables:
  PYTHONPATH: '$PYTHONPATH:$(System.DefaultWorkingDirectory)/django'
  DATABASE_URL: 'mssql://SA:MyPassword42@localhost:1433/default?isolation_level=read committed&driver=ODBC Driver 17 for SQL Server'
  DATABASE_URL_OTHER: 'mssql://SA:MyPassword42@localhost:1433/other?isolation_level=read committed&driver=ODBC Driver 17 for SQL Server'
  python.version: '3.6'
  TOXENV: py

jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-18.04

    strategy:
      matrix:
        Python 3.7 Linux:
          python.version: '3.7'
          tox.env: 'py37-django22'
        Python 3.6 Linux:
          python.version: '3.6'
          tox.env: 'py36-django22'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "$(python.version)"
        displayName: Use Python $(python.version)

      - script: |
          docker pull mcr.microsoft.com/mssql/server:2017-latest-ubuntu
          docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=MyPassword42' -p 1433:1433 -d mcr.microsoft.com/mssql/server:2017-latest-ubuntu
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17 g++ unixodbc-dev
        displayName: Install SQL Server

      - script: |
          python -m pip install --upgrade pip wheel setuptools
          pip install tox
          git clone https://github.com/django/django.git
        displayName: Install requirements

      - script: tox -e $(tox.env)
        displayName: Run tox
  